config/routes.rb
Rails.application.routes.draw do
  resources :social_stats
  post '/callback/stats'

  root 'social_stats#index'
end

app/models/social_stat.rb
class SocialStat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
	skip_before_action :verify_authenticity_token

	# POST /callback/stats
	def stats
		if SocialStat.where(site_id: social_stat_params["site_id"]).blank?
			@social_stat = SocialStat.new(social_stat_params)
			@social_stat.save
			render nothing: true
		else
			@social_stat = SocialStat.find_by(site_id: params["site_id"])
			@social_stat.update(social_stat_params)
			render nothing: true
		end
	end

private

	def social_stat_params
     	params.permit(:site_id, :is_multisite, :wordpress_version, :plugin_version).tap do |whitelisted|
       		whitelisted[:plugin_settings] = params[:plugin_settings]
       		whitelisted[:api_connection_status] = params[:api_connection_status]
     	end
    end
end

app/controllers/social_stats_controller.rb
class SocialStatsController < ApplicationController
  http_basic_authenticate_with name: Rails.application.secrets.basic_auth_name, password: Rails.application.secrets.basic_auth_password 
  before_action :set_social_stat, only: [:show, :edit, :update, :destroy]

  # POST /social_stats
  # POST /social_stats.json
  def create
    @social_stat = SocialStat.new(social_stat_params)
    respond_to do |format|
      if @social_stat.save
        format.html { redirect_to @social_stat, notice: 'Social stat was successfully created.' }
        format.json { render :show, status: :created, location: @social_stat }
      else
        format.html { render :new }
        format.json { render json: @social_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_stats/1
  # PATCH/PUT /social_stats/1.json
  def update
    respond_to do |format|
      if @social_stat.update(social_stat_params)
        format.html { redirect_to @social_stat, notice: 'Social stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_stat }
      else
        format.html { render :edit }
        format.json { render json: @social_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /social_stats
  # GET /social_stats.json
  def index
    @social_stats = SocialStat.all
  end

  # GET /social_stats/1
  # GET /social_stats/1.json
  def show
  end

  # GET /social_stats/new
  def new
    @social_stat = SocialStat.new
  end

  # GET /social_stats/1/edit
  def edit
  end

  # DELETE /social_stats/1
  # DELETE /social_stats/1.json
  def destroy
    @social_stat.destroy
    respond_to do |format|
      format.html { redirect_to social_stats_url, notice: 'Social stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_stat
      @social_stat = SocialStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def social_stat_params
      params.permit(:site_id, :is_multisite, :wordpressp_version, :plugin_version).tap do |whitelisted|
        whitelisted[:plugin_settings] = params[:plugin_settings]
        whitelisted[:api_connection_status] = params[:api_connection_status]
      end
    end
end

app/helpers/callback_helper.rb
module CallbackHelper
end

app/helpers/social_stats_helper.rb
module SocialStatsHelper
end

app/views/data_display/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialMetricsServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/social_stats/_form.html.erb
<%= form_for(@social_stat) do |f| %>
  <% if @social_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@social_stat.errors.count, "error") %> prohibited this social_stat from being saved:</h2>

      <ul>
      <% @social_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_id %><br>
    <%= f.text_field :site_id %>
  </div>
  <div class="field">
    <%= f.label :is_multisite %><br>
    <%= f.check_box :is_multisite %>
  </div>
  <div class="field">
    <%= f.label :wordpress_version %><br>
    <%= f.text_field :wordpress_version %>
  </div>
  <div class="field">
    <%= f.label :plugin_version %><br>
    <%= f.text_field :plugin_version %>
  </div>
  <div class="field">
    <%= f.label :plugin_settings %><br>
    <%= f.text_field :plugin_settings %>
  </div>
  <div class="field">
    <%= f.label :api_connection_status %><br>
    <%= f.text_field :api_connection_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/social_stats/edit.html.erb
<h1>Editing social_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @social_stat %> |
<%= link_to 'Back', social_stats_path %>

app/views/social_stats/index.html.erb
<h1>Listing social_stats</h1>

<table>
  <thead>
    <tr>
      <th>Site</th>
      <th>Is multisite</th>
      <th>Wp version</th>
      <th>Plugin version</th>
      <th>Plugin settings</th>
      <th>Conn status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_stats.each do |social_stat| %>
      <tr>
        <td><%= social_stat.site_id %></td>
        <td><%= social_stat.is_multisite %></td>
        <td><%= social_stat.wordpress_version %></td>
        <td><%= social_stat.plugin_version %></td>
        <td><%= social_stat.plugin_settings %></td>
        <td><%= social_stat.api_connection_status %></td>
        <td><%= link_to 'Show', social_stat %></td>
        <td><%= link_to 'Edit', edit_social_stat_path(social_stat) %></td>
        <td><%= link_to 'Destroy', social_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Social stat', new_social_stat_path %>

app/views/social_stats/new.html.erb
<h1>New social_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', social_stats_path %>

app/views/social_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @social_stat.site_id %>
</p>

<p>
  <strong>Is multisite:</strong>
  <%= @social_stat.is_multisite %>
</p>

<p>
  <strong>Wp version:</strong>
  <%= @social_stat.wordpress_version %>
</p>

<p>
  <strong>Plugin version:</strong>
  <%= @social_stat.plugin_version %>
</p>

<p>
  <strong>Plugin settings:</strong>
  <%= @social_stat.plugin_settings %>
</p>

<p>
  <strong>Conn status:</strong>
  <%= @social_stat.api_connection_status %>
</p>

<%= link_to 'Edit', edit_social_stat_path(@social_stat) %> |
<%= link_to 'Back', social_stats_path %>